package cal.projeteq3.glucose.model;

public enum Departement {
    GESTION_DE_COMMERCES,
    SOINS_INFIRMIERS,
    TECHNIQUES_DEDUCATION_A_LENFANCE,
    TECHNIQUES_DEDUCATION_SPECIALISEE,
    TECHNIQUES_DINHALOTHERAPIE,
    TECHNIQUES_DE_BIOECOLOGIE,
    TECHNIQUES_DE_BUREAUTIQUE,
    TECHNIQUES_DE_COMPTABILITE_ET_DE_GESTION,
    TECHNIQUES_DE_GENIE_MECANIQUE,
    TECHNIQUES_DE_LINFORMATIQUE_GESTION_DE_RESEAUX_INFORMATIQUES,
    TECHNIQUES_DE_LINFORMATIQUE_INFORMATIQUE_DE_GESTION,
    TECHNIQUES_DE_LABORATOIRE_BIOTECHNOLOGIES,
    TECHNIQUES_DE_PHYSIOTHERAPIE,
    TECHNIQUES_POLICIERES,
    TECHNIQUES_DE_SANTE_ANIMALE,
    TECHNIQUES_DE_TRAVAIL_SOCIAL,
    TECHNOLOGIE_DANALYSES_BIOMEDICALES,
    TECHNOLOGIE_DE_LELECTRONIQUE_INDUSTRIELLE,
    TECHNOLOGIE_DE_LELECTRONIQUE_TELECOMMUNICATION,
    TECHNOLOGIE_DE_MAINTENANCE_INDUSTRIELLE,
    TECHNOLOGIE_DE_SYSTEMES_ORDINES,
    TECHNOLOGIE_DU_GENIE_CIVIL

}
